version: '3.8'

services:
  # GitHub Actions Runner
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    restart: unless-stopped
    environment:
      - REPO_URL=${GITHUB_REPOSITORY}
      - RUNNER_TOKEN=${GITHUB_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS}
      - RUNNER_WORK_DIRECTORY=${RUNNER_WORK_DIRECTORY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/runner:/opt/hostedtoolcache
      - ${RUNNER_WORK_DIRECTORY}:${RUNNER_WORK_DIRECTORY}
      - ./logs:/var/log/github-runner
    networks:
      - runner-network

volumes:

networks:
  runner-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 