version: '3.8'

services:
  # GitHub Actions Runner
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    restart: unless-stopped
    environment:
      - REPO_URL=${GITHUB_REPOSITORY}
      - RUNNER_TOKEN=${GITHUB_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS}
      - RUNNER_WORK_DIRECTORY=${RUNNER_WORK_DIRECTORY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/runner:/opt/hostedtoolcache
      - ${RUNNER_WORK_DIRECTORY}:${RUNNER_WORK_DIRECTORY}
      - ./logs:/var/log/github-runner
    networks:
      - runner-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/ssl:/etc/ssl
      - ./logs/nginx:/var/log/nginx
    networks:
      - runner-network
    depends_on:
      - github-runner

  # Let's Encrypt SSL Certificate Manager
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./config/ssl:/etc/letsencrypt
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    command: certonly --webroot --webroot-path=/var/www/html --email ${SSL_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_NAME}
    networks:
      - runner-network

volumes:

networks:
  runner-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 